#include "../lib/string.hpp"
#include <algorithm>
#include <gtest/gtest.h>

TEST(stringTest, stringTest_prefix_function1)
{
    std::vector<size_t> vans{0, 0, 1};
    EXPECT_EQ(agoh::prefix_function("aba"), vans);
}

TEST(stringTest, stringTest_prefix_function2)
{
    std::vector<size_t> vans{0, 1, 2, 3, 4};
    EXPECT_EQ(agoh::prefix_function("aaaaa"), vans);
}

TEST(stringTest, stringTest_kmp1)
{
    std::vector<size_t> vans{0, 2};
    EXPECT_EQ(agoh::kmp("abababc", "aba"), vans);
}

TEST(stringTest, stringTest_kmp2)
{
    std::vector<size_t> vans{
        2,    119,  220,  323,  423,  530,  636,  736,  836,  941,  1043, 1155, 1255, 1368, 1470, 1581,
        1688, 1791, 1892, 2028, 2134, 2238, 2338, 2439, 2543, 2643, 2743, 2843, 2944, 3046, 3147, 3247,
        3347, 3458, 3559, 3659, 3762, 3862, 3971, 4075, 4200, 4300, 4405, 4507, 4607, 4709, 4809, 4915,
        5018, 5119, 5222, 5331, 5434, 5534, 5634, 5737, 5849, 5961, 6063, 6176, 6277, 6380, 6481, 6592,
        6695, 6799, 6906, 7013, 7113, 7221, 7324, 7424, 7530, 7646, 7756, 7856, 7959, 8059, 8177, 8281,
        8399, 8499, 8601, 8703, 8807, 8907, 9007, 9108, 9208, 9309, 9409, 9513, 9613, 9719, 9820,
    };
    for(auto&& i : vans)
        --i;
    EXPECT_EQ(
        agoh::kmp(
            "BABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBCCBB"
            "CACBBCCCCAABABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBA"
            "CBCBCCBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBC"
            "CCCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAB"
            "BCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBBAACCAA"
            "BBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCACBCBBA"
            "BBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCAC"
            "ABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBA"
            "ACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABCABABBCCACABABBAA"
            "CBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCACABBCCACABABBAACBAC"
            "CBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCABCBACAAACABBCCACABABB"
            "AACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBAC"
            "CBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCBBBACCCABAAABBCCACABAB"
            "BAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBAABBCCACABABBAAC"
            "BACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBACCBCBCABBABBCCACABA"
            "BBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCACABCBBABBCCACAB"
            "ABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCBABBCCACABABB"
            "AACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABBCCACABABBAACBA"
            "CCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABCBACCCBBAABBCACBAABA"
            "BCBACACAACAABABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBB"
            "ACBCBCCCCBCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBB"
            "ACBCBCCACABABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBAC"
            "BCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCB"
            "ABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBACCAB"
            "BCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACA"
            "BABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAA"
            "CBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCB"
            "ABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABBCCACABABBAACBACCBABCCA"
            "CCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBAABBCCACABABBAACBACCBABCCACCCB"
            "AACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABBCCACABABBAACBACCBABCCACCCBAACBC"
            "ABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACC"
            "BACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABA"
            "CCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABCABACACAAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCB"
            "ACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABA"
            "CCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCA"
            "CACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACAC"
            "ABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBC"
            "CCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAAABCCBBBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABC"
            "BBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABACABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBB"
            "CCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCACACACBACAACBCCBABABBCCBBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCB"
            "ACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABAC"
            "CACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBCBCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACC"
            "ACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCA"
            "CACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABC"
            "BBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCC"
            "CACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCA"
            "CBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCA"
            "CBCBBCAACBABCAACBBCACCCBBACBCBCCACBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBC"
            "BBCAACBABCAACBBCACCCBBACBCBCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAA"
            "CBABCAACBBCACCCBBACBCBCCBAAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBA"
            "BCAACBBCACCCBBACBCBCCAABAACBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAA"
            "CBABCAACBBCACCCBBACBCBCCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBA"
            "BCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACB"
            "BCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCC"
            "BBACBCBCCCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBA"
            "CBCBCCCACCCACCBAAAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCA"
            "CCCBBACBCBCCBAAABACBBABCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCA"
            "ACBBCACCCBBACBCBCCBBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBB"
            "CACCCBBACBCBCCCCAABABCBBCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBA"
            "BCAACBBCACCCBBACBCBCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAAC"
            "BBCACCCBBACBCBCCCABABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBC"
            "ACCCBBACBCBCCBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCB"
            "BACBCBCCAACAACABBBCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBC"
            "ACCCBBACBCBCCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACC"
            "CBBACBCBCCBCCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCB"
            "BACBCBCCBBACBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCC"
            "BBACBCBCCACBCABAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACC"
            "CBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACB"
            "CBCCCAABBCACABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBA"
            "CBCBCCBBBABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBC"
            "BCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAAC"
            "BCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCB"
            "ABBBCACAABABCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBB"
            "ACBCBCCABCACBBACCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCAC"
            "CCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBAC"
            "BCBCCCCAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCB"
            "CCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAACA"
            "CCAABBAACBCBBCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCB"
            "BACBCBCCABCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBA"
            "CBCBCCBABACBACCACCCCBCBCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCA"
            "ACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCA"
            "CCCBBACBCBCCBCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCB"
            "BACBCBCCAAABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACB"
            "CBCCBBCCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCB"
            "CCABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBC"
            "CACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABBCCACAB"
            "ABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAAC"
            "BACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCAABBCCACABABBAACBACCB"
            "ABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCAC"
            "CCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBABBABBCCACABABBAACBACCBABCCACCC"
            "BAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCABBCCACABABBAACBACCBABCCACCCBAACBC"
            "ABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCCACCCABBCCACABABBAACBACCBABCCACCCBAACBC"
            "ABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCBABBCCACABABBAACBACCBABCCACCCBAACBCABAAC"
            "CBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCCCBCBCAACCBABCABABABCBABABCABCCBBCCCBBCBACBCAC"
            "ACCCABACBCBBBACCAAABCCBBBCCCACBCBBBB",
            "ABBCCACABABBAACBACCBABCCACCCBAACBCABAACCBACABACCACCACACABCBBCCCACCCACBCBBCAACBABCAACBBCACCCBBACBCBCC"),
        vans);
}
